data <- read.csv("climate_news03.csv")

data$X<-gsub("<.*?>","",data$X)
data$X<-gsub("\t","",data$X)
data$X<-gsub("[!#$%*,:;<=>@_`|‘~{}&]", " ", data$X)
data$X<-gsub("rdquo|gt|lt|nbsp|amp|quot|apos","",data$X)
data$X<-gsub("  "," ",data$X)
data$X<-gsub("\\^"," ",data$X)
data$X<-gsub("ㅠ|ㅜ|ㅡ"," ",data$X)
data$X<-gsub("\"|\n|+","",data$X)
data$X<-gsub("\\+","",data$X)
data$X<-gsub("/|!|\\*|\\+|\\@"," ",data$X)
data$X<-gsub("'","",data$X)
data$X<-gsub("\"","",data$X)
data$X<-gsub("=","",data$X)
data$X<-gsub("~|;|<|>","",data$X)
data$X<-gsub("\\?","",data$X)
data$X<-gsub("\\[.*?\\]","",data$X)
data$X<-gsub("\\(.*?\\)","",data$X)
data$X<-gsub("\\(|\\)"," ",data$X)
data$X<-gsub("\\]|\\[|\\(|\\)|:|-|\\,|\\."," ",data$X)
data$X<-gsub("\\!","",data$X)
data$X<-gsub("”|“|’|·","",data$X)

write.csv(data, "climate_news03_preAll.csv")

